"""
Manticore Report Generator

Takes Shannon's findings + Manticore chain synthesis output and produces
a HackerOne-style professional security assessment report.
"""

import json
import os
import sys
from datetime import datetime
from pathlib import Path


SEVERITY_EMOJI = {
    "CRITICAL": "🔴",
    "HIGH": "🟠",
    "MEDIUM": "🟡",
    "LOW": "🔵",
    "INFORMATIONAL": "⚪",
}

REPORT_TEMPLATE = """# Security Assessment Report

**Generated by:** Manticore AI Pentesting Agent
**Date:** {date}
**Target:** {target}
**Model:** Qwen2.5-72B-Instruct on AMD Instinct MI300X

---

## Executive Summary

{executive_summary}

### Risk Overview

| Severity | Chain Findings | Individual Findings |
|----------|---------------|---------------------|
| 🔴 Critical | {critical_chains} | {critical_individual} |
| 🟠 High | {high_chains} | {high_individual} |
| 🟡 Medium | {medium_chains} | {medium_individual} |
| 🔵 Low | {low_chains} | {low_individual} |

---

## Manticore Chain Findings

> These findings represent compound attack paths identified by Manticore's chain synthesis engine.
> Severity ratings reflect the **combined exploitability** of chained vulnerabilities,
> not individual CVSS scores.

{chain_findings}

---

## Individual Findings

{individual_findings}

---

## Methodology

This assessment was conducted using Manticore, an autonomous AI pentesting agent built on AMD MI300X GPUs.

**Pipeline phases:**
1. Pre-Recon — Static source code analysis and architecture mapping
2. Recon — Live attack surface enumeration
3. Vulnerability Analysis — 5 parallel agents (Injection, XSS, Auth, Authorization, SSRF)
4. Exploitation — Playwright-driven proof-of-concept execution
5. Chain Synthesis — Long-context reasoning across all findings (Qwen2.5-72B, AMD MI300X)
6. Reporting — HackerOne-style report generation

**Chain Synthesis:** Manticore sends all findings simultaneously in a single inference call
(80,000-150,000 tokens) to Qwen2.5-72B running locally on AMD Instinct MI300X (192GB VRAM).
This single-pass analysis identifies compound attack paths invisible to per-finding scanners.

---

*This report was generated for authorized security testing purposes only.*
"""

CHAIN_TEMPLATE = """### {id}: {title}

**Severity:** {severity_emoji} {severity} (CVSS {cvss_score})
**CVSS Vector:** `{cvss_vector}`
**CWE:** {cwe_ids}
**Status:** Confirmed — Live Proof of Concept

#### Severity Upgrade

| | Before Chain Analysis | After Chain Analysis |
|--|----------------------|---------------------|
| **Rating** | {ratings_before} | **{severity_after}** |
| **Assessment** | Isolated findings | Compound kill path |

#### Summary

{summary}

#### Impact

{impact}

#### Affected Endpoints

{affected_endpoints}

#### Steps to Reproduce

{steps}

#### Proof of Concept

Automated chain execution via Playwright confirmed. See attached PoC recording.

#### Remediation

{remediation}

---
"""


def format_chain(chain: dict) -> str:
    import json as _json
    severity = chain.get("severity", "HIGH")
    ratings_before = " | ".join(chain.get("severity_before", {}).get("ratings", ["Unknown"]))
    steps_raw = chain.get("steps") or chain.get("playwright_steps", [])
    if steps_raw and isinstance(steps_raw[0], dict):
        steps = "\n".join(f"{i+1}. {s.get('note', _json.dumps(s))}" for i, s in enumerate(steps_raw))
    else:
        steps = "\n".join(f"{i+1}. {step}" for i, step in enumerate(steps_raw))
    endpoints = "\n".join(f"- `{ep}`" for ep in chain.get("affected_endpoints", []))
    cwe_ids = ", ".join(chain.get("cwe_ids", []))

    return CHAIN_TEMPLATE.format(
        id=chain.get("id", "MANTICORE-001"),
        title=chain.get("title", "Untitled Chain"),
        severity_emoji=SEVERITY_EMOJI.get(severity, "⚪"),
        severity=severity,
        cvss_score=chain.get("cvss_score", 0.0),
        cvss_vector=chain.get("cvss_vector", "N/A"),
        cwe_ids=cwe_ids or "N/A",
        ratings_before=ratings_before,
        severity_after=chain.get("severity_after", severity),
        summary=chain.get("summary", ""),
        impact=chain.get("impact", ""),
        affected_endpoints=endpoints or "- See steps to reproduce",
        steps=steps,
        remediation=chain.get("remediation", ""),
    )


def load_findings_report(deliverables_dir: str) -> str:
    report_path = os.path.join(deliverables_dir, "comprehensive_security_assessment_report.md")
    if os.path.exists(report_path):
        with open(report_path) as f:
            return f.read()
    return "_Individual findings report not found. Run the full scanning pipeline first._"


def build_executive_summary(chains: dict, target: str) -> str:
    total = chains.get("total_chains", 0)
    critical = chains.get("critical_count", 0)
    high = chains.get("high_count", 0)

    if total == 0:
        return f"Security assessment of **{target}** completed. No compound attack chains were identified. Review individual findings below."

    summary = f"Security assessment of **{target}** identified **{total} compound attack chain(s)** through Manticore's chain synthesis analysis.\n\n"

    if critical > 0:
        summary += f"**{critical} CRITICAL chain(s)** require immediate remediation. "
        summary += "These represent confirmed kill paths where an attacker can chain multiple vulnerabilities to achieve maximum impact.\n\n"

    if high > 0:
        summary += f"**{high} HIGH severity chain(s)** identified requiring urgent attention.\n\n"

    summary += "Manticore's chain synthesis identified attack paths that individual vulnerability scanners missed by analyzing all findings simultaneously in a single long-context reasoning pass on AMD MI300X hardware."
    return summary


def generate_report(chains_path: str, deliverables_dir: str, target: str, output_path: str) -> None:
    with open(chains_path) as f:
        chains = json.load(f)

    chain_list = chains.get("chains", [])
    chain_findings_md = "\n".join(format_chain(c) for c in chain_list) if chain_list else "_No compound chains identified._"

    shannon_report = load_findings_report(deliverables_dir)

    severity_counts = {"CRITICAL": 0, "HIGH": 0, "MEDIUM": 0, "LOW": 0}
    for chain in chain_list:
        sev = chain.get("severity", "").upper()
        if sev in severity_counts:
            severity_counts[sev] += 1

    report = REPORT_TEMPLATE.format(
        date=datetime.now().strftime("%Y-%m-%d %H:%M UTC"),
        target=target,
        executive_summary=build_executive_summary(chains, target),
        critical_chains=severity_counts["CRITICAL"],
        high_chains=severity_counts["HIGH"],
        medium_chains=severity_counts["MEDIUM"],
        low_chains=severity_counts["LOW"],
        critical_individual="See below",
        high_individual="See below",
        medium_individual="See below",
        low_individual="See below",
        chain_findings=chain_findings_md,
        individual_findings=shannon_report,
    )

    with open(output_path, "w") as f:
        f.write(report)

    print(f"[Manticore] Report written to {output_path}")


if __name__ == "__main__":
    if len(sys.argv) < 4:
        print("Usage: python report.py <chains.json> <deliverables_dir> <target_url> [output_path]")
        sys.exit(1)

    chains_path = sys.argv[1]
    deliverables_dir = sys.argv[2]
    target = sys.argv[3]
    output_path = sys.argv[4] if len(sys.argv) > 4 else os.path.join(deliverables_dir, "manticore_report.md")

    generate_report(chains_path, deliverables_dir, target, output_path)
